language: cpp
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - build-essential
    - libbluetooth-dev
    - libudev-dev
    - libusb-1.0-0-dev
env:
  global:
  - DEBUG_CORE_DUMP="true"
  matrix:
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="amd64" MAIN_BUILD="true"
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
matrix:
  fast_finish: true
  exclude:
  - os: osx
    env: PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
branches:
  only:
  - "/^v[0-9]/"
before_install:
- ulimit -c unlimited -S
- PACKAGER_URL="https://meshblu-connector.octoblu.com/tools/packager/latest"
- curl -fsS "${PACKAGER_URL}/travis_install_node.sh" -o /tmp/travis_install_node.sh
- chmod +x /tmp/travis_install_node.sh
- ". /tmp/travis_install_node.sh"
- if [ "$TRAVIS_OS_NAME" == "linux" -a "$MAIN_BUILD" == "true" ]; then export NPM_PUBLISH="true"; fi
install:
- npm install || echo "This may failed but we don't care"
script:
- npm test || echo "This may failed but we don't care"
before_deploy:
- rm -rf deploy/*
- mkdir -p deploy
- npm install meshblu-connector-schema-generator
- npm run generate:schema
- cp schemas.json deploy
deploy:
- provider: releases
  api_key:
    secure: "hdqygDcKK6k9S+DGWfj1MCms+yL+KRTaT9uYUy303RNQY9YaTBfGWQNGYkWgim2zkoTxD7dxsk5RxjB0YEweEp8V7StIqgvXBTZxA2H5ZtrEtDy3mxwpPli2QsIC2yo4RnpB/s9zACCrrzhNVYcWz/IANBSgsJK5EyUk6gT+kCjr2sHYbK+zLMZVA+VzYebrkbo264oKC2jiqBCUgfBRjHDl6XAw3NnvDriGcYA0ngKE6se6obhz6r7X6TeY1ZayLI6OIyjnb6muHLXRSbp3YYN5b6OlNfdGwH9bVZ8UaViSbhnjhFNPKO3Q/faPFqMDq9rabJ2Tg/7AfBHfeHIN55diUC/ATHiuqwUWr8HkbPaeu5yonNa2pN184qqzLpbAsRXKZzOk2CKyexrlYqlp115gttCs6Ger+U5SHN69qU+2r4/QlXOh/XL/AH0dU4rxC1ZH/fXCkJfz+xG1sf98DarWWTdYrCJhpXo1qxkxv47xVvUziTMefHZSczCXJSXsxUgI0S+BXhltMP7rk26ZW/LL1/jNcIH1IV4jZ6uC04ieVImMZf8ilq5Wz7TQtj7LC2PBx9MaUgUZvX8eYHFTeTxI+0T54B/hST7/+gZjYCXpJ4Fn84COTD7qUGuIz5m+kOBu3ncvB3uQnpa8ZKoLEEMfQy8Rvy2LoxhDD0nJaEc="
  file_glob: true
  file:
  - "deploy/*"
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: "A6Y3NCPkZ6Kg4bsxZjCGeEmVypOBo7JJ6FsPdsy084gWv4iOykrj5ikS+PL+C4ADZ159yp0r6QFMB1sRtTLTLm551hHcGTFcJUY36Vi2zDrcSWpRdU+U3pqtKIR861oF6c2qvtY2CRy/6Ll1B6oKpD9ffaHWDo5UBsqyWVH9VCHc2Lz/xpnqE9gM8tW5UEzJB7YIoOvTZVdH6i2vZcNUOvRy6OZDC3THjy7B2oMYIl22mrbLiFhttCk27KZbEVptuf2f+3PIaXkvrEc5CAHaUqEKW809u6yi/tW1OPKFCokruHot5M4C2Pk139IZ6wWokheXUd1kdtF8q8oq2Hmvy+IwPyB2OsDylTd2nRx4IM/Ji2OxyEE+eZeCOSbf25xc/dVbGSDYbDbuA5hNdsW6j/iq+MDjZw2MKJOVVRuHaVhpSXGsfzDPti/NICbzmqqcpsGShzuiWAl5/DUSAvfbcNhb2n90SS394ncaNov4neVjVa330WDRPa1ZgV5ME9Gwfyq4DlAcnrOAlvIvUB0L5IX5Pok+cPSo9fJdin0QFPFPoLAisFanEgl6M6dJzCqDGRSrWPlkMvigH3AnjY8UA1KXqen47T23CPELAj//m4SKa+fk6YzcNi+M1Twm8ZavMDG/J5TveLod+9WMuvN9ubFI1UYAZ8LbuQDFw+0uV4Y="
  on:
    tags: true
    condition: "$NPM_PUBLISH = true"
